### ISSUE TITLE
deal with recoded multiple frames *.dat data

### ISSUE THREAD

**Issue by yujianyuanhaha** [austingreisman/TI_AWR1443#1]
greetings,

wonderful job and work for my *.dat data.

But I notice it alway output single-frame information, whenever I record more than 100-seconds  *.dat file. I believe the *.dat size grow with longer recording time.

could you help to check on that?

Best

Jet

**Comment by aridergreisman** [comment]
Hi @yujianyuanhaha,

I'm a bit confused about what the problem is specifically? Can the python script not process a .dat file that's larger than 100MB?

The script was designed to process the data sequentially, so the first captured information will always be processed first.

Austin

**Comment by yujianyuanhaha** [comment]
@austingreisman check with this [10s record data size 26k](https://drive.google.com/file/d/11uzGzLMRF8kPcqeGRo-2ukmdQKAr7DjH/view?usp=sharing), and another [100s record data size 286k](https://drive.google.com/file/d/11ud7yQ7MZGcu4ycB7k3BEgdgC6L-bWuC/view?usp=sharing).        Both of them output single frame only

**Comment by aridergreisman** [comment]
I don’t believe I had that issue with mine. I won’t be able to attempt a fix for at least a week, possibly more.

Can you give some info on your set up?
1. SDK
2. Radar Unit
3. Operating system
4. Python Version

**Comment by yujianyuanhaha** [comment]
@austingreisman i guess the bug come from this line
```
def tlvHeader(data, skip_range=False, skip_stats=False):
       ...
        magic = b'\x02\x01\x04\x03\x06\x05\x08\x07'
        offset = data.find(magic)
       ....

```

the`.find()` only return lowest index of magic string, but in fact there are many of them, each stands for a frame.

**Comment by yujianyuanhaha** [comment]
@austingreisman mine setup is
1. SDK v1.02
2. Radar AWR1443
3. Chrome-based mmW Demo Visualizer 2.0
4.  Python version 3.7.0

Best

Jet

**Comment by aridergreisman** [comment]
I tested your .DAT files and also only got one frame, but the number was strange.

This python script is only for code higher than SDK V1. There was another python script that I found that was created for SDK V1, but I was unable to re-find it on the TI site.

**Comment by yujianyuanhaha** [comment]
@austingreisman okay, let me upgrade the SDK and check it.

**Comment by aridergreisman** [comment]
> @austingreisman okay, let me upgrade the SDK and check it.

Did the upgrade help?
